# Generated by Django 5.1.3 on 2024-11-24 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название департамента или отдела', max_length=64, unique=True)),
                ('description', models.TextField(blank=True, help_text='Описание отдела')),
                ('manager', models.ForeignKey(blank=True, help_text='Пользователь, который управляет отделом', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_departments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, help_text='Должность сотрудника', max_length=128)),
                ('hire_date', models.DateField(blank=True, help_text='Дата приема на работу', null=True)),
                ('department', models.ForeignKey(blank=True, help_text='Отдел, в котором работает сотрудник', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='structure_app.department')),
                ('user', models.OneToOneField(help_text='Пользователь системы', on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название проекта', max_length=128, unique=True)),
                ('description', models.TextField(blank=True, help_text='Описание проекта')),
                ('start_date', models.DateField(help_text='Дата начала проекта')),
                ('end_date', models.DateField(blank=True, help_text='Дата завершения проекта', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Активен ли проект')),
                ('department', models.ForeignKey(help_text='Отдел, ответственный за проект', on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='structure_app.department')),
            ],
        ),
    ]
